# Load required packages and functions
# ------------------------------------
myPaths <- .libPaths()
myPaths <- c(myPaths, "/exports/igmm/eddie/dunlop-lab/BradleyH/R/x86_64-pc-linux-gnu-library/4.0.2")
myPaths <- c(myPaths[2], myPaths[1])
.libPaths(myPaths)
library(Seurat)
library(methods)
library(edgeR)
library(cowplot)
library(ggpubr)
library(ggplot2)
library(ggfortify)
library(devtools)

library(BiocGenerics, pos=length(search()))
library(S4Vectors, pos=length(search()))
library(DelayedArray, pos=length(search()))
library(MAST)

library(cccd)
library(cowplot)
library(data.table)
library(DirichletReg)
library(doParallel)
library(dplyr)
library(expm)
library(Hmisc)
library(ggbeeswarm)
library(ggplot2)
library(ggrepel)
library(ggsignif)
library(gtools)
library(MASS)
library(Matrix)
library(Matrix.utils)
library(rsvd)
library(Rtsne)
library(RColorBrewer)
library(sva)
library(tibble)
library(tidyverse)
library(tidyr)
library(wordspace)
